Auto increment version for `lr_trie`
versatus/integral-db pull request #10
Opened 2023-08-29 23:52 UTC by eureka-cpu

adds auto incrementalism of version each time the tree is updated, this avoids us needing to do this else where causing possible bugs or unintended behaviour or usage of the library

2023-08-30 14:27 UTC, nopestack commented on lr_trie/src/absorb_op.rs
> +                match self.put_value_set(vec![key_val.to_owned()], *vers + 1) {
blocking: do a checked addition instead so the version doesn't overflow.

https://docs.rs/num/latest/num/trait.CheckedAdd.html

2023-08-30 14:29 UTC, nopestack commented on lr_trie/src/trie.rs
> +                    .expect("could not retrieve version from trie"),
blocking: how do you plan to address these calls to `expect` in the short term? Remember this component is the foundation for other components and these can't have this library panic underneath,

2023-08-30 14:32 UTC, nopestack requested changes
Looks good overall, only one minor change and blocking change requested and another concern that needs to be addresssed. Other than that It'd be nice if the version update interval, i.e. the `+1` is a constant instead of a magic number

2023-08-31 17:49 UTC, eureka-cpu commented on lr_trie/src/trie.rs
> +                    .expect("could not retrieve version from trie"),
Used `unwrap_or_default` though I'm not sure if the default would ever be used, and if it did I'm not sure if it's the behaviour we would expect this to be. The rest of the code surrounding storage does have this behaviour though. It makes me wonder if we should be using `expect` for the time being since we won't catch potential bugs if things will always just default.

Just food for thought, it's probably okay for now.

2023-08-31 17:50 UTC, eureka-cpu commented on lr_trie/src/absorb_op.rs
> +                match self.put_value_set(vec![key_val.to_owned()], *vers + 1) {
Done, but also left a comment describing potential issues with overflow

2023-08-31 17:50 UTC, merged